### ISSUE TITLE
When using multiple before templates, do not require the type present in a single before template to be present for all matches

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-templating#119]
As seen on:
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/520

The `AssertEqualWithMessage` rule from Picnic's EPS contains a number of different before templates, each with different argument types.
- https://github.com/PicnicSupermarket/error-prone-support/blob/75a9786f8ff6fc4b514610e3d2447551002f2e40/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java#L417-L478

The now generated preconditions with 1.19.1 require the type from just one of those before templates to be present for all before a match.
```java
            return Preconditions.check(
                    Preconditions.and(
                        new UsesType<>("java.util.Map", true),
                        new UsesMethod<>("org.testng.Assert assertEquals(..)", true)
                    ),
                    javaVisitor
            );
```

Ideally we adjust the preconditions such that the `UsesType` `Map` is either optional, or fully absent, unless that's present on _all_ before templates.

**Comment by knutwannheden** [comment]
Interesting! I wasn't aware of this possibility. I think we should then indeed skip the UsesType unless all before templates have it. Is that the only thing that needs to be changed to make these Refaster recipes wirk?

**Comment by timtebeek** [comment]
I haven't explored this yet, but I think that's the only change indeed. Note that the input template here as a mix of primitives and classes; any adjustments would need to account for that, but I think it ought to be straightforward. I've asked the team to have a look.
