### ISSUE TITLE
Refaster style recipes cannot match types that require transitive dependencies to be loaded

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-templating#86]
This parser:
```java
JavaTemplate.builder("#{any(com.azure.cosmos.CosmosClientBuilder)}.endpoint(\"boo\").userAgentSuffix(\"test\").buildAsyncClient()")
                .javaParser(JavaParser.fromJavaVersion().classpath("azure-cosmos"))
                .build()
```
Cannot be used to match a method invocation of `CosmosClientBuilder.buildAsyncClient()` because the method its parser produces lacks type information. `CosmosClientBuilder` is defined within the jar "azure-cosmos", but also requires "azure-core" for the java compiler to type attribute it.

This is because `JavaParser.fromJavaVersion().classpath()` does not look up transitive dependencies of the named artifact, so "azure-core" is absent from the classpath.

[This test](https://github.com/openrewrite/rewrite/blob/bade688c8c6647f7d4cce1077417f021735ca835/rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java) can be used to reproduce the issue. Changing `JavaParser.fromJavaVersion().classpath(JavaParser.fromRuntimeClasspath())` resolves this problem because the full runtime classpath has both "azure-cosmos" and "azure-core".

**Comment by Gueorgi** [comment]
All my testing used already the JavaParser.fromJavaVersion().classpath(JavaParser.runtimeClasspath()) in the defaults spec.recipe for the generated recipe template. And it never worked - we debugged it few day ago and last week as well - that is how it was setup. Still does not work.

**Comment by Gueorgi** [comment]
@sambsnyd the test specified here: https://github.com/openrewrite/rewrite/blob/bade688c8c6647f7d4cce1077417f021735ca835/rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java#L164C8-L164C176
is not valid. It does not target any CosmosClientBuilder invocation but specific ".endpoint(\"boo\").userAgentSuffix(\"test\")" - i.e. in client code these additional calls on the builder can come at any order and there are a lot more additional calls that can be there or not. A proper test would use:

"#{builder:any(com.azure.cosmos.CosmosClientBuilder)}.buildAsyncClient()" to match code that may or may not use endpoint or userAgentSuffix on the builder.

And that is still failing for me with latest versions and with avaParser.fromJavaVersion().classpath(JavaParser.runtimeClasspath()) being used for the last 2 weeks.

**Comment by Gueorgi** [comment]
@sambsnyd 

Actually I copied your test in my local and modified it (not looking for specific userAgent, endpoint).... and it works! :)

Looks like the issue was indeed was with setting the classpath - the big difference was that I was doing it in the defaults:
`public void defaults(RecipeSpec spec) {
        spec.recipe(new ReplaceSyncClientBuilderRecipe()).parser(JavaParser.fromJavaVersion()
                        .classpath(JavaParser.runtimeClasspath()));
 }`
 
 where it works only if I use it like you:
 `rewriteRun(
          spec -> spec.recipe(toRecipe(() -> new JavaVisitor<>() {
                final JavaTemplate template = JavaTemplate.builder("#{any(com.azure.cosmos.CosmosClientBuilder)}.buildAsyncClient()")
                  .javaParser(JavaParser.fromJavaVersion().classpath(JavaParser.runtimeClasspath()))
                  .build();
                final JavaTemplate replacement = JavaTemplate.builder("null")
                  .build();

                @Override
                public J visitMethodInvocation(J.MethodInvocation method, ExecutionContext executionContext) {
                    JavaTemplate.Matcher matcher = template.matcher(getCursor());
                    if(matcher.find()) {
                        return replacement.apply(getCursor(), method.getCoordinates().replace());
                    }
                    return super.visitMethodInvocation(method, executionContext);
                }
            }))
            .parser(JavaParser.fromJavaVersion().classpath(JavaParser.runtimeClasspath())) .....`
