### ISSUE TITLE
💡 Add "@Generated" annotation to generated code

### ISSUE THREAD

**Issue by mbruggmann** [openrewrite/rewrite-templating#96]
## What problem are you trying to solve?
The classes generated by the rewrite-templating annotation processor fail some of our [errorprone](https://errorprone.info/) rules.

## Describe the solution you'd like
Add a `@javax.annotation.processing.Generated("org.openrewrite.java.template.processor.RefasterTemplateProcessor")` annotation to classes produced by the annotation processor.
This will make it so errorprone ignores that code if the `-XepDisableWarningsInGeneratedCode` argument is passed.

## Have you considered any alternatives or workarounds?
Open for other suggestions!

## Are you interested in contributing this feature to OpenRewrite
Possibly, but I'm not familiar with the codebase.

**Comment by timtebeek** [comment]
Fixed in https://github.com/openrewrite/rewrite-templating/pull/97 Thanks a lot! We might want to keep an eye on if that dependency is available to Java 9+ projects, but we can tackle that if it comes to it.
